# This configuration is not right! It's not secure at all!
# TODO: update the cofiguration!
---
- name: Copy my.cnf MySQL configuration for root user.
  template:
    src: "../templates/root.my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart MySQL

- name: Update MySQL `bind-address` configuration
  lineinfile:
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    regexp: '^#?\s*bind-address\s+=\s+.+'
    line: 'bind-address = 0.0.0.0'
    state: present
  notify:
    - Restart MySQL

- name: Update MySQL `mysqlx-bind-address` configuration
  lineinfile:
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    regexp: '^#?\s*mysqlx-bind-address\s+=\s+.+'
    line: 'mysqlx-bind-address = 0.0.0.0'
    state: present
  notify:
    - Restart MySQL