---
- name: MySQL Installation - set the default root pass
  debconf:
    name: mysql-server-5.7
    question: mysql-server/root_password
    vtype: password
    value: "{{ mysql_root_pass }}"

- name: MySQL Installation - confirm the default root pass
  debconf:
    name: mysql-server-5.7
    question: mysql-server/root_password_again
    vtype: password
    value: "{{ mysql_root_pass }}"
    
# TODO: Install a specific version of mysql 5.7
- name: MySQL Installation - install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-common
    - mysql-server
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: MySQL Installation - install mysql python library for ansible
  pip:
    name: pymysql
    state: present

- include_tasks: configure.yml
- include_tasks: secure_installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml