---
- hosts: docker
  become: true
  gather_facts: yes
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - 'apt-transport-https'
        - 'ca-certificates'
        - 'curl'
        - 'gnupg'
        - 'lsb-release'
        - 'software-properties-common'
        - 'python3-pip'
        - 'virtualenv'
        - 'python3-setuptools'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - 'docker-ce'
        - 'docker-ce-cli'
        - 'containerd.io'

    - name: Install Docker Module for Python to use by Ansible
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        auto_remove: yes
        published_ports:
          - 80:80