---
- name: Install basic packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - tmux
    - curl
    - wget
    - htop
    - zip
    - unzip
    - pigz
    - supervisor