---
- name: Ensure `docker` group is present
  group:
    name: docker
    state: present

- name: Create the non-root user account
  user:
    name: "{{ user_name }}"
    password: "{{ user_pass }}"
    shell: /bin/bash
    update_password: on_create
    groups:
      - docker
    append: yes
