---
- hosts: mysql
  become: true
  gather_facts: yes

  tasks:
    - name: Install basic utilities
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        autoclean: yes
      loop:
        - vim
        - tmux
        - curl
        - wget
        - htop
        - zip
        - unzip
        - pigz

    - name: Configure MySQL pass
      debconf:
        name: "mysql-server-5.7"
        question: "mysql-server/root_password password"
        value: root
        vtype: string

    - name: Configure MySQL pass 2
      debconf:
        name: "mysql-server-5.7"
        question: "mysql-server/root_password_again password"
        value: root
        vtype: string

    - name: Install MySQL
      environment:
        DEBIAN_FRONTEND: noninteractive
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Flush existing firewall rules
      iptables:
        flush: true

    - name: Firewall rule - allow all loopback traffic
      iptables:
        action: append
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Firewall rule - allow established connections
      iptables:
        action: append
        chain: INPUT
        ctstate:
          - RELATED
          - ESTABLISHED
        jump: ACCEPT

    - name: "Firewall rule - allow SSH"
      iptables:
        action: append
        chain: INPUT
        protocol: tcp
        destination_port: "22"
        jump: ACCEPT

    - name: "Firewall rule - allow connection to MySQL from specific IPs"
      iptables:
        action: append
        chain: INPUT
        protocol: tcp
        destination_port: "3306"
        source: "{{ item }}"
        jump: ACCEPT
      loop:
        - ""

    - name: "Firewall rule - drop any traffic without rule"
      iptables:
        action: append
        chain: INPUT
        jump: DROP

    - name: Install `netfilter-persistent` && `iptables-persistent` packages
      apt:
        name: "{{item}}"
        state: present
      loop:
        - iptables-persistent
        - netfilter-persistent
      when: ansible_os_family == "Debian"

    - name: Save iptables
      service:
        name: netfilter-persistent
        args: save

    - name: Restart iptables
      service:
        name: netfilter-persistent
        state: restarted

    - name: Install fail2ban
      environment:
        DEBIAN_FRONTEND: noninteractive
      apt:
        name: fail2ban
        state: present
        update_cache: yes