---
- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == 'Debian' or ansible_os_family == "Ubuntu"

- name: Upgading all packange (CentOS)
  yum:
    name: '*'  
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Install a few more packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - htop